name: 'Doc Build'
description: 'Build & Validate Sphinx Documentation'
author: 'andreasofthings'
inputs:
  docs:
    description: 'Where to find docs'
    default: 'docs'
  dest:
    description: 'Where to put docs'
    default: 'build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output }}
