name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs:
  output:
    description: 'Output for directory'
    default: 'directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output }}
