name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs:
  docs:
    description: 'Where to find docs'
    default: 'docs'
  dest:
    description: 'Where to put docs'
    default: 'build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output }}
