name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs:
  where-to:
    description: 'Where to write to'
    default: 'directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output }}
